// words.js

const DifficultyLevel = {
    BEGINNER: '초급',
    INTERMEDIATE: '중급',
    ADVANCED: '고급',
};

const LEVEL_ORDER = [
    DifficultyLevel.BEGINNER,
    DifficultyLevel.INTERMEDIATE,
    DifficultyLevel.ADVANCED,
];

const WORDS_DATA = [
    // --- 초급 (Beginner) - 100단어 ---
    { id: 'b_1', english: 'famous', korean: '유명한', level: DifficultyLevel.BEGINNER },
    { id: 'b_2', english: 'develop', korean: '발전시키다', level: DifficultyLevel.BEGINNER },
    { id: 'b_3', english: 'kitchen', korean: '부엌', level: DifficultyLevel.BEGINNER },
    { id: 'b_4', english: 'beautiful', korean: '아름다운', level: DifficultyLevel.BEGINNER },
    { id: 'b_5', english: 'government', korean: '정부', level: DifficultyLevel.BEGINNER },
    { id: 'b_6', english: 'holiday', korean: '휴일', level: DifficultyLevel.BEGINNER },
    { id: 'b_7', english: 'century', korean: '세기', level: DifficultyLevel.BEGINNER },
    { id: 'b_8', english: 'distance', korean: '거리', level: DifficultyLevel.BEGINNER },
    { id: 'b_9', english: 'breath', korean: '숨', level: DifficultyLevel.BEGINNER },
    { id: 'b_10', english: 'modern', korean: '현대의', level: DifficultyLevel.BEGINNER },
    { id: 'b_11', english: 'adventure', korean: '모험', level: DifficultyLevel.BEGINNER },
    { id: 'b_12', english: 'express', korean: '표현하다', level: DifficultyLevel.BEGINNER },
    { id: 'b_13', english: 'foreign', korean: '외국의', level: DifficultyLevel.BEGINNER },
    { id: 'b_14', english: 'choice', korean: '선택', level: DifficultyLevel.BEGINNER },
    { id: 'b_15', english: 'especially', korean: '특히', level: DifficultyLevel.BEGINNER },
    { id: 'b_16', english: 'energy', korean: '에너지', level: DifficultyLevel.BEGINNER },
    { id: 'b_17', english: 'business', korean: '사업', level: DifficultyLevel.BEGINNER },
    { id: 'b_18', english: 'customer', korean: '고객', level: DifficultyLevel.BEGINNER },
    { id: 'b_19', english: 'natural', korean: '자연의', level: DifficultyLevel.BEGINNER },
    { id: 'b_20', english: 'general', korean: '일반적인', level: DifficultyLevel.BEGINNER },
    { id: 'b_21', english: 'electric', korean: '전기의', level: DifficultyLevel.BEGINNER },
    { id: 'b_22', english: 'complete', korean: '완성하다', level: DifficultyLevel.BEGINNER },
    { id: 'b_23', english: 'dangerous', korean: '위험한', level: DifficultyLevel.BEGINNER },
    { id: 'b_24', english: 'library', korean: '도서관', level: DifficultyLevel.BEGINNER },
    { id: 'b_25', english: 'important', korean: '중요한', level: DifficultyLevel.BEGINNER },
    { id: 'b_26', english: 'exercise', korean: '운동', level: DifficultyLevel.BEGINNER },
    { id: 'b_27', english: 'instead', korean: '대신에', level: DifficultyLevel.BEGINNER },
    { id: 'b_28', english: 'corner', korean: '모서리', level: DifficultyLevel.BEGINNER },
    { id: 'b_29', english: 'evening', korean: '저녁', level: DifficultyLevel.BEGINNER },
    { id: 'b_30', english: 'current', korean: '현재의', level: DifficultyLevel.BEGINNER },
    { id: 'b_31', english: 'culture', korean: '문화', level: DifficultyLevel.BEGINNER },
    { id: 'b_32', english: 'equipment', korean: '장비', level: DifficultyLevel.BEGINNER },
    { id: 'b_33', english: 'frequently', korean: '자주', level: DifficultyLevel.BEGINNER },
    { id: 'b_34', english: 'climate', korean: '기후', level: DifficultyLevel.BEGINNER },
    { id: 'b_35', english: 'explain', korean: '설명하다', level: DifficultyLevel.BEGINNER },
    { id: 'b_36', english: 'factory', korean: '공장', level: DifficultyLevel.BEGINNER },
    { id: 'b_37', english: 'control', korean: '통제하다', level: DifficultyLevel.BEGINNER },
    { id: 'b_38', english: 'citizen', korean: '시민', level: DifficultyLevel.BEGINNER },
    { id: 'b_39', english: 'failure', korean: '실패', level: DifficultyLevel.BEGINNER },
    { id: 'b_40', english: 'ground', korean: '땅', level: DifficultyLevel.BEGINNER },
    { id: 'b_41', english: 'degree', korean: '정도', level: DifficultyLevel.BEGINNER },
    { id: 'b_42', english: 'capital', korean: '수도', level: DifficultyLevel.BEGINNER },
    { id: 'b_43', english: 'compare', korean: '비교하다', level: DifficultyLevel.BEGINNER },
    { id: 'b_44', english: 'careful', korean: '조심스러운', level: DifficultyLevel.BEGINNER },
    { id: 'b_45', english: 'director', korean: '감독', level: DifficultyLevel.BEGINNER },
    { id: 'b_46', english: 'example', korean: '예', level: DifficultyLevel.BEGINNER },
    { id: 'b_47', english: 'industry', korean: '산업', level: DifficultyLevel.BEGINNER },
    { id: 'b_48', english: 'material', korean: '재료', level: DifficultyLevel.BEGINNER },
    { id: 'b_49', english: 'opinion', korean: '의견', level: DifficultyLevel.BEGINNER },
    { id: 'b_50', english: 'character', korean: '인물', level: DifficultyLevel.BEGINNER },
    { id: 'b_51', english: 'difference', korean: '차이', level: DifficultyLevel.BEGINNER },
    { id: 'b_52', english: 'bridge', korean: '다리', level: DifficultyLevel.BEGINNER },
    { id: 'b_53', english: 'advice', korean: '조언', level: DifficultyLevel.BEGINNER },
    { id: 'b_54', english: 'create', korean: '창조하다', level: DifficultyLevel.BEGINNER },
    { id: 'b_55', english: 'animal', korean: '동물', level: DifficultyLevel.BEGINNER },
    { id: 'b_56', english: 'difficult', korean: '어려운', level: DifficultyLevel.BEGINNER },
    { id: 'b_57', english: 'forest', korean: '숲', level: DifficultyLevel.BEGINNER },
    { id: 'b_58', english: 'however', korean: '그러나', level: DifficultyLevel.BEGINNER },
    { id: 'b_59', english: 'opportunity', korean: '기회', level: DifficultyLevel.BEGINNER },
    { id: 'b_60', english: 'courage', korean: '용기', level: DifficultyLevel.BEGINNER },
    { id: 'b_61', english: 'information', korean: '정보', level: DifficultyLevel.BEGINNER },
    { id: 'b_62', english: 'finally', korean: '마침내', level: DifficultyLevel.BEGINNER },
    { id: 'b_63', english: 'address', korean: '주소', level: DifficultyLevel.BEGINNER },
    { id: 'b_64', english: 'machine', korean: '기계', level: DifficultyLevel.BEGINNER },
    { id: 'b_65', english: 'memory', korean: '기억', level: DifficultyLevel.BEGINNER },
    { id: 'b_66', english: 'healthy', korean: '건강한', level: DifficultyLevel.BEGINNER },
    { id: 'b_67', english: 'freedom', korean: '자유', level: DifficultyLevel.BEGINNER },
    { id: 'b_68', english: 'future', korean: '미래', level: DifficultyLevel.BEGINNER },
    { id: 'b_69', english: 'improve', korean: '개선하다', level: DifficultyLevel.BEGINNER },
    { id: 'b_70', english: 'hospital', korean: '병원', level: DifficultyLevel.BEGINNER },
    { id: 'b_71', english: 'article', korean: '기사', level: DifficultyLevel.BEGINNER },
    { id: 'b_72', english: 'ability', korean: '능력', level: DifficultyLevel.BEGINNER },
    { id: 'b_73', english: 'benefit', korean: '이익', level: DifficultyLevel.BEGINNER },
    { id: 'b_74', english: 'language', korean: '언어', level: DifficultyLevel.BEGINNER },
    { id: 'b_75', english: 'medical', korean: '의학의', level: DifficultyLevel.BEGINNER },
    { id: 'b_76', english: 'common', korean: '흔한', level: DifficultyLevel.BEGINNER },
    { id: 'b_77', english: 'available', korean: '이용할 수 있는', level: DifficultyLevel.BEGINNER },
    { id: 'b_78', english: 'decision', korean: '결정', level: DifficultyLevel.BEGINNER },
    { id: 'b_79', english: 'necessary', korean: '필요한', level: DifficultyLevel.BEGINNER },
    { id: 'b_80', english: 'celebrate', korean: '축하하다', level: DifficultyLevel.BEGINNER },
    { id: 'b_81', english: 'education', korean: '교육', level: DifficultyLevel.BEGINNER },
    { id: 'b_82', english: 'employee', korean: '직원', level: DifficultyLevel.BEGINNER },
    { id: 'b_83', english: 'journey', korean: '여행', level: DifficultyLevel.BEGINNER },
    { id: 'b_84', english: 'happen', korean: '일어나다', level: DifficultyLevel.BEGINNER },
    { id: 'b_85', english: 'neighbor', korean: '이웃', level: DifficultyLevel.BEGINNER },
    { id: 'b_86', english: 'mistake', korean: '실수', level: DifficultyLevel.BEGINNER },
    { id: 'b_87', english: 'accept', korean: '받아들이다', level: DifficultyLevel.BEGINNER },
    { id: 'b_88', english: 'appear', korean: '나타나다', level: DifficultyLevel.BEGINNER },
    { id: 'b_89', english: 'environment', korean: '환경', level: DifficultyLevel.BEGINNER },
    { id: 'b_90', english: 'economic', korean: '경제의', level: DifficultyLevel.BEGINNER },
    { id: 'b_91', english: 'depend', korean: '의존하다', level: DifficultyLevel.BEGINNER },
    { id: 'b_92', english: 'athlete', korean: '운동선수', level: DifficultyLevel.BEGINNER },
    { id: 'b_93', english: 'discuss', korean: '토론하다', level: DifficultyLevel.BEGINNER },
    { id: 'b_94', english: 'interest', korean: '관심', level: DifficultyLevel.BEGINNER },
    { id: 'b_95', english: 'history', korean: '역사', level: DifficultyLevel.BEGINNER },
    { id: 'b_96', english: 'experience', korean: '경험', level: DifficultyLevel.BEGINNER },
    { id: 'b_97', english: 'imagine', korean: '상상하다', level: DifficultyLevel.BEGINNER },
    { id: 'b_98', english: 'include', korean: '포함하다', level: DifficultyLevel.BEGINNER },
    { id: 'b_99', english: 'increase', korean: '증가하다', level: DifficultyLevel.BEGINNER },
    { id: 'b_100', english: 'chance', korean: '기회', level: DifficultyLevel.BEGINNER },

    // --- 중급 (Intermediate) - 100단어 ---
    { id: 'i_1', english: 'challenge', korean: '도전', level: DifficultyLevel.INTERMEDIATE },
    { id: 'i_2', english: 'conference', korean: '회의', level: DifficultyLevel.INTERMEDIATE },
    { id: 'i_3', english: 'approach', korean: '접근하다', level: DifficultyLevel.INTERMEDIATE },
    { id: 'i_4', english: 'agriculture', korean: '농업', level: DifficultyLevel.INTERMEDIATE },
    { id: 'i_5', english: 'basically', korean: '기본적으로', level: DifficultyLevel.INTERMEDIATE },
    { id: 'i_6', english: 'category', korean: '범주', level: DifficultyLevel.INTERMEDIATE },
    { id: 'i_7', english: 'commercial', korean: '상업의', level: DifficultyLevel.INTERMEDIATE },
    { id: 'i_8', english: 'ancient', korean: '고대의', level: DifficultyLevel.INTERMEDIATE },
    { id: 'i_9', english: 'authority', korean: '권위', level: DifficultyLevel.INTERMEDIATE },
    { id: 'i_10', english: 'capacity', korean: '능력', level: DifficultyLevel.INTERMEDIATE },
    { id: 'i_11', english: 'democracy', korean: '민주주의', level: DifficultyLevel.INTERMEDIATE },
    { id: 'i_12', english: 'construct', korean: '건설하다', level: DifficultyLevel.INTERMEDIATE },
    { id: 'i_13', english: 'although', korean: '비록 ~이지만', level: DifficultyLevel.INTERMEDIATE },
    { id: 'i_14', english: 'anxiety', korean: '불안', level: DifficultyLevel.INTERMEDIATE },
    { id: 'i_15', english: 'calendar', korean: '달력', level: DifficultyLevel.INTERMEDIATE },
    { id: 'i_16', english: 'attitude', korean: '태도', level: DifficultyLevel.INTERMEDIATE },
    { id: 'i_17', english: 'analyze', korean: '분석하다', level: DifficultyLevel.INTERMEDIATE },
    { id: 'i_18', english: 'accomplish', korean: '달성하다', level: DifficultyLevel.INTERMEDIATE },
    { id: 'i_19', english: 'creative', korean: '창의적인', level: DifficultyLevel.INTERMEDIATE },
    { id: 'i_20', english: 'campaign', korean: '캠페인', level: DifficultyLevel.INTERMEDIATE },
    { id: 'i_21', english: 'colleague', korean: '동료', level: DifficultyLevel.INTERMEDIATE },
    { id: 'i_22', english: 'accurate', korean: '정확한', level: DifficultyLevel.INTERMEDIATE },
    { id: 'i_23', english: 'border', korean: '국경', level: DifficultyLevel.INTERMEDIATE },
    { id: 'i_24', english: 'communicate', korean: '소통하다', level: DifficultyLevel.INTERMEDIATE },
    { id: 'i_25', english: 'condition', korean: '조건', level: DifficultyLevel.INTERMEDIATE },
    { id: 'i_26', english: 'community', korean: '공동체', level: DifficultyLevel.INTERMEDIATE },
    { id: 'i_27', english: 'acquire', korean: '획득하다', level: DifficultyLevel.INTERMEDIATE },
    { id: 'i_28', english: 'appreciate', korean: '감사하다', level: DifficultyLevel.INTERMEDIATE },
    { id: 'i_29', english: 'concept', korean: '개념', level: DifficultyLevel.INTERMEDIATE },
    { id: 'i_30', english: 'collect', korean: '수집하다', level: DifficultyLevel.INTERMEDIATE },
    { id: 'i_31', english: 'budget', korean: '예산', level: DifficultyLevel.INTERMEDIATE },
    { id: 'i_32', english: 'belong', korean: '속하다', level: DifficultyLevel.INTERMEDIATE },
    { id: 'i_33', english: 'classify', korean: '분류하다', level: DifficultyLevel.INTERMEDIATE },
    { id: 'i_34', english: 'congress', korean: '의회', level: DifficultyLevel.INTERMEDIATE },
    { id: 'i_35', english: 'contain', korean: '포함하다', level: DifficultyLevel.INTERMEDIATE },
    { id: 'i_36', english: 'confidence', korean: '자신감', level: DifficultyLevel.INTERMEDIATE },
    { id: 'i_37', english: 'criminal', korean: '범죄자', level: DifficultyLevel.INTERMEDIATE },
    { id: 'i_38', english: 'absolutely', korean: '절대적으로', level: DifficultyLevel.INTERMEDIATE },
    { id: 'i_39', english: 'behave', korean: '행동하다', level: DifficultyLevel.INTERMEDIATE },
    { id: 'i_40', english: 'circumstance', korean: '상황', level: DifficultyLevel.INTERMEDIATE },
    { id: 'i_41', english: 'constant', korean: '지속적인', level: DifficultyLevel.INTERMEDIATE },
    { id: 'i_42', english: 'connection', korean: '연결', level: DifficultyLevel.INTERMEDIATE },
    { id: 'i_43', english: 'cooperate', korean: '협력하다', level: DifficultyLevel.INTERMEDIATE },
    { id: 'i_44', english: 'critical', korean: '비판적인', level: DifficultyLevel.INTERMEDIATE },
    { id: 'i_45', english: 'approve', korean: '승인하다', level: DifficultyLevel.INTERMEDIATE },
    { id: 'i_46', english: 'continue', korean: '계속하다', level: DifficultyLevel.INTERMEDIATE },
    { id: 'i_47', english: 'commission', korean: '위원회', level: DifficultyLevel.INTERMEDIATE },
    { id: 'i_48', english: 'determine', korean: '결정하다', level: DifficultyLevel.INTERMEDIATE },
    { id: 'i_49', english: 'attempt', korean: '시도하다', level: DifficultyLevel.INTERMEDIATE },
    { id: 'i_50', english: 'domestic', korean: '국내의', level: DifficultyLevel.INTERMEDIATE },
    { id: 'i_51', english: 'disaster', korean: '재난', level: DifficultyLevel.INTERMEDIATE },
    { id: 'i_52', english: 'advance', korean: '발전하다', level: DifficultyLevel.INTERMEDIATE },
    { id: 'i_53', english: 'convince', korean: '설득하다', level: DifficultyLevel.INTERMEDIATE },
    { id: 'i_54', english: 'civilization', korean: '문명', level: DifficultyLevel.INTERMEDIATE },
    { id: 'i_55', english: 'consist', korean: '구성되다', level: DifficultyLevel.INTERMEDIATE },
    { id: 'i_56', english: 'consider', korean: '고려하다', level: DifficultyLevel.INTERMEDIATE },
    { id: 'i_57', english: 'contribute', korean: '기여하다', level: DifficultyLevel.INTERMEDIATE },
    { id: 'i_58', english: 'describe', korean: '묘사하다', level: DifficultyLevel.INTERMEDIATE },
    { id: 'i_59', english: 'concentrate', korean: '집중하다', level: DifficultyLevel.INTERMEDIATE },
    { id: 'i_60', english: 'drama', korean: '드라마', level: DifficultyLevel.INTERMEDIATE },
    { id: 'i_61', english: 'department', korean: '부서', level: DifficultyLevel.INTERMEDIATE },
    { id: 'i_62', english: 'candidate', korean: '후보자', level: DifficultyLevel.INTERMEDIATE },
    { id: 'i_63', english: 'argue', korean: '논쟁하다', level: DifficultyLevel.INTERMEDIATE },
    { id: 'i_64', english: 'ceremony', korean: '의식', level: DifficultyLevel.INTERMEDIATE },
    { id: 'i_65', english: 'beyond', korean: '너머에', level: DifficultyLevel.INTERMEDIATE },
    { id: 'i_66', english: 'conflict', korean: '갈등', level: DifficultyLevel.INTERMEDIATE },
    { id: 'i_67', english: 'curious', korean: '호기심 있는', level: DifficultyLevel.INTERMEDIATE },
    { id: 'i_68', english: 'destroy', korean: '파괴하다', level: DifficultyLevel.INTERMEDIATE },
    { id: 'i_69', english: 'distribute', korean: '분배하다', level: DifficultyLevel.INTERMEDIATE },
    { id: 'i_70', english: 'discover', korean: '발견하다', level: DifficultyLevel.INTERMEDIATE },
    { id: 'i_71', english: 'admission', korean: '입학', level: DifficultyLevel.INTERMEDIATE },
    { id: 'i_72', english: 'criticism', korean: '비판', level: DifficultyLevel.INTERMEDIATE },
    { id: 'i_73', english: 'damage', korean: '손상', level: DifficultyLevel.INTERMEDIATE },
    { id: 'i_74', english: 'demonstrate', korean: '증명하다', level: DifficultyLevel.INTERMEDIATE },
    { id: 'i_75', english: 'efficient', korean: '효율적인', level: DifficultyLevel.INTERMEDIATE },
    { id: 'i_76', english: 'earn', korean: '벌다', level: DifficultyLevel.INTERMEDIATE },
    { id: 'i_77', english: 'election', korean: '선거', level: DifficultyLevel.INTERMEDIATE },
    { id: 'i_78', english: 'establish', korean: '설립하다', level: DifficultyLevel.INTERMEDIATE },
    { id: 'i_79', english: 'engineer', korean: '기술자', level: DifficultyLevel.INTERMEDIATE },
    { id: 'i_80', english: 'announce', korean: '발표하다', level: DifficultyLevel.INTERMEDIATE },
    { id: 'i_81', english: 'enormous', korean: '거대한', level: DifficultyLevel.INTERMEDIATE },
    { id: 'i_82', english: 'emotion', korean: '감정', level: DifficultyLevel.INTERMEDIATE },
    { id: 'i_83', english: 'emergency', korean: '응급상황', level: DifficultyLevel.INTERMEDIATE },
    { id: 'i_84', english: 'empire', korean: '제국', level: DifficultyLevel.INTERMEDIATE },
    { id: 'i_85', english: 'advantage', korean: '장점', level: DifficultyLevel.INTERMEDIATE },
    { id: 'i_86', english: 'evidence', korean: '증거', level: DifficultyLevel.INTERMEDIATE },
    { id: 'i_87', english: 'examine', korean: '검사하다', level: DifficultyLevel.INTERMEDIATE },
    { id: 'i_88', english: 'exactly', korean: '정확히', level: DifficultyLevel.INTERMEDIATE },
    { id: 'i_89', english: 'exchange', korean: '교환하다', level: DifficultyLevel.INTERMEDIATE },
    { id: 'i_90', english: 'experiment', korean: '실험', level: DifficultyLevel.INTERMEDIATE },
    { id: 'i_91', english: 'explore', korean: '탐험하다', level: DifficultyLevel.INTERMEDIATE },
    { id: 'i_92', english: 'exist', korean: '존재하다', level: DifficultyLevel.INTERMEDIATE },
    { id: 'i_93', english: 'expert', korean: '전문가', level: DifficultyLevel.INTERMEDIATE },
    { id: 'i_94', english: 'extremely', korean: '극도로', level: DifficultyLevel.INTERMEDIATE },
    { id: 'i_95', english: 'familiar', korean: '친숙한', level: DifficultyLevel.INTERMEDIATE },
    { id: 'i_96', english: 'fantasy', korean: '환상', level: DifficultyLevel.INTERMEDIATE },
    { id: 'i_97', english: 'feature', korean: '특징', level: DifficultyLevel.INTERMEDIATE },
    { id: 'i_98', english: 'flexible', korean: '유연한', level: DifficultyLevel.INTERMEDIATE },
    { id: 'i_99', english: 'framework', korean: '틀', level: DifficultyLevel.INTERMEDIATE },
    { id: 'i_100', english: 'disease', korean: '질병', level: DifficultyLevel.INTERMEDIATE },

    // --- 고급 (Advanced) - 100단어 ---
    { id: 'a_1', english: 'phenomenon', korean: '현상', level: DifficultyLevel.ADVANCED },
    { id: 'a_2', english: 'elaborate', korean: '정교한', level: DifficultyLevel.ADVANCED },
    { id: 'a_3', english: 'contemporary', korean: '현대의', level: DifficultyLevel.ADVANCED },
    { id: 'a_4', english: 'autonomous', korean: '자율적인', level: DifficultyLevel.ADVANCED },
    { id: 'a_5', english: 'investigate', korean: '조사하다', level: DifficultyLevel.ADVANCED },
    { id: 'a_6', english: 'methodology', korean: '방법론', level: DifficultyLevel.ADVANCED },
    { id: 'a_7', english: 'deteriorate', korean: '악화되다', level: DifficultyLevel.ADVANCED },
    { id: 'a_8', english: 'constitute', korean: '구성하다', level: DifficultyLevel.ADVANCED },
    { id: 'a_9', english: 'integrate', korean: '통합하다', level: DifficultyLevel.ADVANCED },
    { id: 'a_10', english: 'comprehensive', korean: '포괄적인', level: DifficultyLevel.ADVANCED },
    { id: 'a_11', english: 'crucial', korean: '중요한', level: DifficultyLevel.ADVANCED },
    { id: 'a_12', english: 'facilitate', korean: '촉진하다', level: DifficultyLevel.ADVANCED },
    { id: 'a_13', english: 'arbitrary', korean: '자의적인', level: DifficultyLevel.ADVANCED },
    { id: 'a_14', english: 'dimension', korean: '차원', level: DifficultyLevel.ADVANCED },
    { id: 'a_15', english: 'alternative', korean: '대안', level: DifficultyLevel.ADVANCED },
    { id: 'a_16', english: 'legislative', korean: '법률의', level: DifficultyLevel.ADVANCED },
    { id: 'a_17', english: 'explicit', korean: '명시적인', level: DifficultyLevel.ADVANCED },
    { id: 'a_18', english: 'federal', korean: '연방의', level: DifficultyLevel.ADVANCED },
    { id: 'a_19', english: 'eliminate', korean: '제거하다', level: DifficultyLevel.ADVANCED },
    { id: 'a_20', english: 'abstract', korean: '추상적인', level: DifficultyLevel.ADVANCED },
    { id: 'a_21', english: 'notion', korean: '개념', level: DifficultyLevel.ADVANCED },
    { id: 'a_22', english: 'inevitable', korean: '불가피한', level: DifficultyLevel.ADVANCED },
    { id: 'a_23', english: 'hypothesis', korean: '가설', level: DifficultyLevel.ADVANCED },
    { id: 'a_24', english: 'incorporate', korean: '통합하다', level: DifficultyLevel.ADVANCED },
    { id: 'a_25', english: 'objective', korean: '객관적인', level: DifficultyLevel.ADVANCED },
    { id: 'a_26', english: 'cumulative', korean: '누적적인', level: DifficultyLevel.ADVANCED },
    { id: 'a_27', english: 'generate', korean: '생성하다', level: DifficultyLevel.ADVANCED },
    { id: 'a_28', english: 'dynamic', korean: '역동적인', level: DifficultyLevel.ADVANCED },
    { id: 'a_29', english: 'enhance', korean: '향상시키다', level: DifficultyLevel.ADVANCED },
    { id: 'a_30', english: 'justify', korean: '정당화하다', level: DifficultyLevel.ADVANCED },
    { id: 'a_31', english: 'manipulate', korean: '조작하다', level: DifficultyLevel.ADVANCED },
    { id: 'a_32', english: 'anticipate', korean: '예상하다', level: DifficultyLevel.ADVANCED },
    { id: 'a_33', english: 'acknowledge', korean: '인정하다', level: DifficultyLevel.ADVANCED },
    { id: 'a_34', english: 'identical', korean: '동일한', level: DifficultyLevel.ADVANCED },
    { id: 'a_35', english: 'component', korean: '구성요소', level: DifficultyLevel.ADVANCED },
    { id: 'a_36', english: 'aggressive', korean: '공격적인', level: DifficultyLevel.ADVANCED },
    { id: 'a_37', english: 'fluctuate', korean: '변동하다', level: DifficultyLevel.ADVANCED },
    { id: 'a_38', english: 'deviation', korean: '편차', level: DifficultyLevel.ADVANCED },
    { id: 'a_39', english: 'substantial', korean: '상당한', level: DifficultyLevel.ADVANCED },
    { id: 'a_40', english: 'emerge', korean: '나타나다', level: DifficultyLevel.ADVANCED },
    { id: 'a_41', english: 'derive', korean: '도출하다', level: DifficultyLevel.ADVANCED },
    { id: 'a_42', english: 'fundamental', korean: '근본적인', level: DifficultyLevel.ADVANCED },
    { id: 'a_43', english: 'evaluate', korean: '평가하다', level: DifficultyLevel.ADVANCED },
    { id: 'a_44', english: 'consensus', korean: '합의', level: DifficultyLevel.ADVANCED },
    { id: 'a_45', english: 'exclusive', korean: '독점적인', level: DifficultyLevel.ADVANCED },
    { id: 'a_46', english: 'authentic', korean: '진정한', level: DifficultyLevel.ADVANCED },
    { id: 'a_47', english: 'preliminary', korean: '예비의', level: DifficultyLevel.ADVANCED },
    { id: 'a_48', english: 'advocate', korean: '옹호하다', level: DifficultyLevel.ADVANCED },
    { id: 'a_49', english: 'minimize', korean: '최소화하다', level: DifficultyLevel.ADVANCED },
    { id: 'a_50', english: 'illustrate', korean: '설명하다', level: DifficultyLevel.ADVANCED },
    { id: 'a_51', english: 'conservative', korean: '보수적인', level: DifficultyLevel.ADVANCED },
    { id: 'a_52', english: 'compromise', korean: '타협', level: DifficultyLevel.ADVANCED },
    { id: 'a_53', english: 'barrier', korean: '장벽', level: DifficultyLevel.ADVANCED },
    { id: 'a_54', english: 'correlate', korean: '상관관계', level: DifficultyLevel.ADVANCED },
    { id: 'a_55', english: 'demonstrate', korean: '입증하다', level: DifficultyLevel.ADVANCED }, // 중급 demonstrate와 중복, 고급에서는 더 심화된 의미로 사용될 수 있음
    { id: 'a_56', english: 'allocate', korean: '할당하다', level: DifficultyLevel.ADVANCED },
    { id: 'a_57', english: 'equivalent', korean: '동등한', level: DifficultyLevel.ADVANCED },
    { id: 'a_58', english: 'infrastructure', korean: '인프라', level: DifficultyLevel.ADVANCED },
    { id: 'a_59', english: 'discrimination', korean: '차별', level: DifficultyLevel.ADVANCED },
    { id: 'a_60', english: 'aesthetic', korean: '미적인', level: DifficultyLevel.ADVANCED },
    { id: 'a_61', english: 'ethical', korean: '윤리적인', level: DifficultyLevel.ADVANCED },
    { id: 'a_62', english: 'emphasize', korean: '강조하다', level: DifficultyLevel.ADVANCED },
    { id: 'a_63', english: 'interpret', korean: '해석하다', level: DifficultyLevel.ADVANCED },
    { id: 'a_64', english: 'abundant', korean: '풍부한', level: DifficultyLevel.ADVANCED },
    { id: 'a_65', english: 'dominate', korean: '지배하다', level: DifficultyLevel.ADVANCED },
    { id: 'a_66', english: 'coordinate', korean: '조정하다', level: DifficultyLevel.ADVANCED },
    { id: 'a_67', english: 'eventually', korean: '결국', level: DifficultyLevel.ADVANCED },
    { id: 'a_68', english: 'criteria', korean: '기준', level: DifficultyLevel.ADVANCED },
    { id: 'a_69', english: 'dramatic', korean: '극적인', level: DifficultyLevel.ADVANCED },
    { id: 'a_70', english: 'guarantee', korean: '보장하다', level: DifficultyLevel.ADVANCED },
    { id: 'a_71', english: 'exceed', korean: '초과하다', level: DifficultyLevel.ADVANCED },
    { id: 'a_72', english: 'duration', korean: '지속기간', level: DifficultyLevel.ADVANCED },
    { id: 'a_73', english: 'controversial', korean: '논란의', level: DifficultyLevel.ADVANCED },
    { id: 'a_74', english: 'bizarre', korean: '기괴한', level: DifficultyLevel.ADVANCED },
    { id: 'a_75', english: 'conventional', korean: '관습적인', level: DifficultyLevel.ADVANCED },
    { id: 'a_76', english: 'epidemic', korean: '전염병', level: DifficultyLevel.ADVANCED },
    { id: 'a_77', english: 'adequate', korean: '적절한', level: DifficultyLevel.ADVANCED },
    { id: 'a_78', english: 'imply', korean: '암시하다', level: DifficultyLevel.ADVANCED },
    { id: 'a_79', english: 'abolish', korean: '폐지하다', level: DifficultyLevel.ADVANCED },
    { id: 'a_80', english: 'feasible', korean: '실행 가능한', level: DifficultyLevel.ADVANCED },
    { id: 'a_81', english: 'assembly', korean: '집회', level: DifficultyLevel.ADVANCED },
    { id: 'a_82', english: 'accommodate', korean: '수용하다', level: DifficultyLevel.ADVANCED },
    { id: 'a_83', english: 'assessment', korean: '평가', level: DifficultyLevel.ADVANCED },
    { id: 'a_84', english: 'accelerate', korean: '가속화하다', level: DifficultyLevel.ADVANCED },
    { id: 'a_85', english: 'diminish', korean: '감소하다', level: DifficultyLevel.ADVANCED },
    { id: 'a_86', english: 'distinctive', korean: '독특한', level: DifficultyLevel.ADVANCED },
    { id: 'a_87', english: 'evolve', korean: '진화하다', level: DifficultyLevel.ADVANCED },
    { id: 'a_88', english: 'evidence', korean: '명백한', level: DifficultyLevel.ADVANCED }, // 중급 evidence(증거)와 구분될 수 있도록, 형용사적 의미 강조. 또는 다른 단어로 대체 고려.
    { id: 'a_89', english: 'contemplate', korean: '숙고하다', level: DifficultyLevel.ADVANCED },
    { id: 'a_90', english: 'assumption', korean: '가정', level: DifficultyLevel.ADVANCED },
    { id: 'a_91', english: 'conceive', korean: '개념화하다', level: DifficultyLevel.ADVANCED },
    { id: 'a_92', english: 'indicate', korean: '나타내다', level: DifficultyLevel.ADVANCED },
    { id: 'a_93', english: 'dedicate', korean: '헌신하다', level: DifficultyLevel.ADVANCED },
    { id: 'a_94', english: 'implement', korean: '실행하다', level: DifficultyLevel.ADVANCED },
    { id: 'a_95', english: 'exploit', korean: '이용하다', level: DifficultyLevel.ADVANCED }, // '착취하다' 의미도 있음
    { id: 'a_96', english: 'abandon', korean: '포기하다', level: DifficultyLevel.ADVANCED },
    { id: 'a_97', english: 'consequence', korean: '결과', level: DifficultyLevel.ADVANCED },
    { id: 'a_98', english: 'initiative', korean: '주도권', level: DifficultyLevel.ADVANCED },
    { id: 'a_99', english: 'attribute', korean: '속성', level: DifficultyLevel.ADVANCED }, // 동사 '~의 탓으로 돌리다'와 구분
    { id: 'a_100', english: 'ambiguous', korean: '애매한', level: DifficultyLevel.ADVANCED },
];

// 퀴즈 설정 상수
const QUESTIONS_PER_QUIZ = 20; // 단어 수가 충분하므로 10문제 또는 그 이상으로 조정 가능
const OPTIONS_COUNT = 4;
const LEVEL_UP_THRESHOLD_PERCENTAGE = 70;